### ISSUE TITLE
Please support "virtual"

### ISSUE THREAD

**Issue by neominky** [reactiveui/ReactiveUI.SourceGenerators#122]
**Is your feature request related to a problem? Please describe.**

 I want to use change-tracking functionality like ['ChangeTracking'](https://mfidemraizer.github.io/trackerdog/html/0e46d6ac-6f64-4d54-98fd-3813df42cb8e.htm) or '[trackerdog](https://github.com/joelweiss/ChangeTracking)' together. To use the proxy, properties need to be declared as virtual.

**Describe the solution you'd like**

` 
       [Reactive(SetModifier = AccessModifier.Public, Overridable = true)]
        private string _nodeName;
`

**Comment by PremekTill** [comment]
A similar issue occurs when implementing an abstract or virtual property defined in a base class, where the generated code lacks the override keyword. As such, instead of a simple boolean switch, I would maybe consider something like an InheritanceModifier enum with values of None, Virtual, Override and New to cover all of the possible modifiers (aside from Abstract, which obviously doesn't make sense when generating an implementation).
