### ISSUE TITLE
Remove IsExternalInit

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI.SourceGenerators#96]
As per the comment below we likely should remove the ExternalInit generation in our code, and opt for instead readme.md file changes to suggest the user use one of the different libraries that provide it like PolyFill or ExternalInit etc. 

> @ChrisPulman Hi, this PR seems incomplete/wrong, because it prevents usage of source packages like [Polyfill](https://github.com/SimonCropp/Polyfill) due to duplicate definition of `IsExternalInit`.
> 
> There are some solutions:
> 
> 1. Never add `IsExternalInit` and let the developer choose the `IsExternalInit` implementation (and maybe add a FAQ and issue (closed) for the resulting error message
> 2. Don't emit `IsExternalInit` and just use `get; set;` instead of `get; init;`
> 3. Guard the implementation with a `#if !REACTIVEUI_NO_ISEXTERNALINIT` or something like that
> 4. Allow setting a configuration in the csproj file to deactivate emitting `IsExternalInit`, similar to what [PolySharp](https://github.com/Sergio0694/PolySharp) does

_Originally posted by @fubar-coder in https://github.com/reactiveui/ReactiveUI.SourceGenerators/issues/83#issuecomment-2439771862_

**Comment by fubar-coder** [comment]
Just an additional solution (not preferred):

It seems that using [PolySharp](https://github.com/Sergio0694/PolySharp) works fine, but isn't as "complete" as Polyfill. My assumption is, that the source generator of PolySharp only emits the `IsExternalInit` class if it isn't already defined in the project. This may or may not cause problems, when you have a dependency (library) which defines `IsExternalInit` publicly (due to - for example - a set `PolyPublic` option for Polyfill).

**Comment by glennawatson** [comment]
Normally I use `PrivateAssets="all"` and then normally make use that IsExternalInit is internal only.
